### ISSUE TITLE
warning: the use of `tmpnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by PathosEthosLogos** [matricks/bam#108]
Error log after running "sh make_unix.sh"

compiling using gcc...
/tmp/ccHtrAsZ.o: In function `os_tmpname':
loslib.c:(.text+0x29c): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

**Comment by matricks** [comment]
Not an error. It's a warning that comes from Lua. Upstream issue.
