### ISSUE TITLE
cliquer's cl is wrongly identified as Windows compiler

### ISSUE THREAD

**Issue by rffontenelle** [matricks/bam#113]
[cliquer](https://users.aalto.fi/~pat/cliquer.html) has a binary named `cl`, which has the same name of the Windows compiler. Because of that, when cliquer is installed in a Linux system, Teeworlds wrongly identifies the system as a Windows and the build fails. This was also reported in teeworlds/teeworlds#1503.

As attachment, follows a workaround for this issue: by changing the order of the 'ExecuteSilent' calls and putting gcc and clang before cl, building Teeworlds in Linux is no more. I didn't make a pull request as I'm not sure whether this is the  best solution.

**Environment:**
Distro: Arch Linux 64bit
Packages:  gcc 7.2.0, teeworlds git master, bam master-git, cliquer 1.21

**Files:**
* [build-output.txt](https://github.com/teeworlds/teeworlds/files/1346269/build-output.txt)
* [avoid-cl-on-Linux.patch.txt](https://github.com/matricks/bam/files/1347137/avoid-cl-on-Linux.patch.txt)

**Comment by matricks** [comment]
Fixed with #2a89765
