### ISSUE TITLE
Support for VS 2017 Community Edition in make_win64_msvc.bat

### ISSUE THREAD

**Issue by Fisico** [matricks/bam#126]
Compiling bam with Visual Studio 2017 over make_win64_msvc.bat is not possible.

VS 2017 does not register an environment variable for "VSCOMNTOOLS" like older VS do.

maybe search for VS 2017 in the "program files(x86)" folder?

Default Directory for vcvars.bat:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat

**Comment by BeBopping** [comment]
I believe the solution to this is to modify the vs2017 installation to include the Python native development tools.
1. Launch Visual Studio Installer
2. Modify the installation
3. Select the Python Development workload.
4. Select the python native development tools options
5. Select Modify

Now I'm running into a different issue after compiling, where I try to run bam config, and I get:
bam: error opening 'bam.lua'

This is my first time running this, so any help would be appreciated.

**Comment by EbrahimBGA** [comment]
[make_win64_msvc.bat](https://gist.github.com/EbrahimBGA/ff1be338fd145c630637b90d3b4c2b66)-fixed
**or**
run vcvars64.bat then cd to bam dir.
