### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by Sworddragon** [matricks/bam#16]
I get on Ubuntu some Compiler warnings:

>src/support.c: In function ‘plugin_load’:
src/support.c:257: warning: ISO C forbids conversion of object pointer to function pointer type
/tmp/ccsw9F3h.o: In function `os_tmpname':
loslib.c:(.text+0x51): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

**Comment by matricks** [comment]
Old warnings or lua warnings that I "can't" do anything about at the moment.
