### ISSUE TITLE
node error

### ISSUE THREAD

**Issue by MAP94** [matricks/bam#41]
error: node 'hash.cpp' is depended on itself and is produced by a job

There should be a way to turn off this error. 

Example:
a job produces a md5 hash of  file.cpp and saves it to hash.cpp

```
//version.h
#ifndef NON_HASED_VERSION
    #include "generated/hash.cpp"
    #define GAME_LUA_VERSION_HASH "1.3 " GAME_LUAVERSION_HASH
#endif
#define GAME_LUA_VERSION "1.3"
```

```
//file.cpp
#define NON_HASED_VERSION
#include "version.h"
#undef NON_HASED_VERSION
```

In this case the hased data wont be included

**Comment by matricks** [comment]
No. If you have a job that is dependent on itself you have done something wrong. Why is hash.cpp dependent on itself?
