### ISSUE TITLE
Make build reproducible

### ISSUE THREAD

**Issue by debfx** [matricks/bam#65]
bam uses the C macros __DATE__ and __TIME__,
This makes it impossible to create reproducible (bitwise identical) binaries.

In src/cache.c, would it be enough to use BAM_VERSION_STRING_COMPLETE instead for the cache file header?

**Comment by matricks** [comment]
The version string isn't sufficient as then you can move cache-file 
between systems, need to check pointer size, endianess etc as well. The 
cache file should be bound to the executable and thats why I used the 
DATE and TIME macros. Helps during development if you do changes as 
well.

Is there a problem that you can't compile identical executables?

**Comment by debfx** [comment]
The idea is to be able to verify that a particular binary is really built from the source code.
See https://wiki.debian.org/ReproducibleBuilds/About#Why_do_we_want_reproducible_builds.3F

To achieve that you can't store build timestamps in the binary. That will result in a different binary for every build.

**Comment by matricks** [comment]
Fair point. I'll look into it.

**Comment by matricks** [comment]
This should be fixed with 0.5.0.
