### ISSUE TITLE
bam: error opening 'bam.lua'

### ISSUE THREAD

**Issue by peppelinux** [matricks/bam#83]
root@maker:/home/wert/Progs/bam# lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch

**Comment by matricks** [comment]
Invalid issue.
