### ISSUE TITLE
Add  Visual Studio 2015 support

### ISSUE THREAD

**Issue by heinrich5991** [matricks/bam#85]
Apparantly `bam` doesn't recognize Visual Studio 2015: [Forum post](https://www.teeworlds.com/forum/viewtopic.php?pid=115776).

**Comment by H-M-H** [comment]
Hehe heinrich was faster, according to this https://github.com/matricks/bam/blob/master/make_win32_msvc.bat#L8 VS 2013 doesn't work either

**Comment by msiglreith** [comment]
VS 2013 works as 12 is the internal version number.
VS 2015 has 14 as version number.

**Comment by H-M-H** [comment]
Thanks for correcting me, I didn't know about that. Versionnumbering is always kind of tricky :D. However, in this case VS 2013 should be mentioned in the errormessage.

**Comment by matricks** [comment]
Now fixed
