### ISSUE TITLE
0.5.0 official release?

### ISSUE THREAD

**Issue by ilovezfs** [matricks/bam#94]
Is the v0.5.0 tag the finished release? I wasn't sure since https://matricks.github.io/bam/ still has 0.4.0 posted.

**Comment by matricks** [comment]
That page should be removed and 0.5.0 is a release that is ready

**Comment by ilovezfs** [comment]
@matricks Thanks for clarifying! FYI: https://github.com/Homebrew/homebrew-core/pull/2074
