### ISSUE TITLE
Do not request -t flag when already provided

### ISSUE THREAD

**Issue by rffontenelle** [matricks/bam#96]
After running with `-t` flag, bam again suggests `-t` flag for more details, which would adds nothing to the ouput. The "-t for more detail" could be ommitted in this case. 

> $ bam -t release
> [string "src/base.lua"]:38: this file for version 0.4.x of bam. you are running 0.5.x.
> backtrace:
> string "src/base.lua": CheckVersion global
> bam.lua(1): (null) 
> bam: script error (-t for more detail)

**Comment by matricks** [comment]
Fixed by c021a4c0d86dd0f042bf49046ee6bb51b88b8d96
